# Comments are provided throughout this file to help you get started.
# If you need more help, visit the Docker compose reference guide at
# https://docs.docker.com/compose/compose-file/

# Here the instructions define your application as two services called "todo-app" and “todo-database”
# The service “todo-app” is built from the Dockerfile in the /app directory,
# and the service “todo-database” uses the official MongoDB image
# from Docker Hub - https://hub.docker.com/_/mongo.
# You can add other services your application may depend on here.

services:
  todo-app:
    build:
      context: ./app
    links:
      - todo-database
    #   depends_on:
    #     mongo-setup:
    #       condition: service_completed_successfully
    volumes:
      - ./app:/usr/src/app
      - app_node_modules:/usr/src/app/node_modules
    ports:
      - 3001:3001
    networks:
      - default
      - mylocal-net

  todo-database:
    image: mongo:6
    container_name: todo-database
    hostname: todo-database
    # command: mongod --port 27018 # main branch
    # https://stackoverflow.com/questions/76013265/how-to-do-a-mongodb-6-single-node-replicaset-with-docker-compose
    command: [--replSet, my-replica-set, --bind_ip_all, --port, "27018"]
    ports:
      - 27018:27018
    volumes:
      - mongo_data:/data/db # Maps named volume to internal path
    networks:
      - default
      - mylocal-net
    healthcheck:
      test: test $$(mongosh --port 27018 --quiet --eval "try {rs.initiate({_id:'my-replica-set',members:[{_id:0,host:\"todo-database:27018\"}]})} catch(e) {rs.status().ok}") -eq 1
      interval: 10s
      start_period: 30s
#      interval: 10s
#      timeout: 5s
#      retries: 10
#      start_period: 15s

# mongo-setup:
#   image: mongo:6
# 2. Mount the script so the setup container can execute it
#   volumes:
#     - ./init-replica.js:/init-replica.js
#   networks:
#     - default
#     - mylocal-net
# 3. CRITICAL: Command runs the script using mongosh and then exits.
#    The hostname MUST match the database container name.
#   command: mongosh --host todo-database --port 27018 /init-replica.js
# 4. CRITICAL: Wait for the database to be 'healthy' before running setup
#   depends_on:
#     todo-database:
#       condition: service_healthy

# --- NETWORK DEFINITIONS ---

networks:
  mylocal-net:
    external: true

# --- VOLUME DEFINITIONS ---
volumes:
  # 1. Persistent Data Volume
  mongo_data:
  app_node_modules:
